### ISSUE TITLE
transformer yolo is coming！

### ISSUE THREAD

**Issue by Zigars** [WongKinYiu/yolor#1]
I'm wait for the open!

**Comment by WongKinYiu** [comment]
Oh, we have already integrated transformer/swin-transformer/... to yolo in our private projects.
I think our new transformer based yolo will be released in this year.

**Comment by Zigars** [comment]
wow, I‘m waiting for the released. 
And I have a question about yolor, I saw the fps of yolor-d6 can get 30, which part of the net architectural reduce the inference time? I know you add some new implicit and explicit module, but I saw the parameter and Flops did not reduce. can I get the reason for it?

**Comment by WongKinYiu** [comment]
Compare to YOLOv4-P7, YOLOR-D6 has only 57% FLOPs. This is the main reason it can achieve higher FPS.
And we apply the methods proposed in CSPNet, which reduce the memory bandwidth in inference process (Appendix).

![image](https://user-images.githubusercontent.com/12152972/118419914-00fe3c80-b6f0-11eb-93f9-9ef1deacd85f.png)

**Comment by Zigars** [comment]
oh, sorry about it , maybe I should re-read of the paper and code, I did not  notice the appendix, thanks!

**Comment by RaphaelWag** [comment]
@WongKinYiu are there any updates when you plan to release your transformer/swin-transformer yolo?

**Comment by Splendon** [comment]
@WongKinYiu 
What time would you release yolor with transformer/swin-transformer ?
