### ISSUE TITLE
inference another models like yolor_W6,E6,D6 error

### ISSUE THREAD

**Issue by ehdrndd** [WongKinYiu/yolor#105]
Detecting with `yolor_p6` is fine.

But, another models like 'yolor_W6,E6,D6'

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\KANG\anaconda3\envs\OD\lib\site-packages\torch\serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\KANG\anaconda3\envs\OD\lib\site-packages\torch\serialization.py", line 853, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models.yolo'`

I guess W6,E6,D6 is saved by `torch 1.4`. but now i using `torch 1.7`

Is there any solution not downgrading torch?

**Comment by ehdrndd** [comment]
Thanks. but, i still don't know solution..

In debug mode..
print(torch.load('yolor_w6.pt', map_location=device)['model'])

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\KANG\anaconda3\envs\OD\lib\site-packages\torch\serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\KANG\anaconda3\envs\OD\lib\site-packages\torch\serialization.py", line 853, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models.yolo'`


print(torch.load('yolor_p6.pt', map_location=device)['model'])

`OrderedDict([('module_list.1.Conv2d.weight', tensor([[[[ 7.08389e...='cuda:0')), ('module_list.1.BatchN...m2d.weight', tensor([2.45703, 1.7...='cuda:0')), ('module_list.1.BatchNorm2d.bias', tensor([ 3.51172,  3...='cuda:0')), ('module_list.1.BatchN...nning_mean', tensor([ 3.52287e-03...='cuda:0')), ('module_list.1.BatchN...unning_var', tensor([3.51715e-03,...='cuda:0')), ('module_list.1.BatchN...es_tracked', tensor(0, device='cuda:0')), ('module_list.2.Conv2d.weight', tensor([[[[ 7.91168e...='cuda:0')), ('module_list.2.BatchN...m2d.weight', tensor([1.27051, 1.7...='cuda:0')), ('module_list.2.BatchNorm2d.bias', tensor([ 1.19336, -2...='cuda:0')), ('module_list.2.BatchN...nning_mean', tensor([-1.83984, -0...='cuda:0')), ('module_list.2.BatchN...unning_var', tensor([ 2.45703,  0...='cuda:0')), ('module_list.2.BatchN...es_tracked', tensor(0, device='cuda:0')), ('module_list.3.Conv2d.weight', tensor([[[[ 0.00136]...='cuda:0')), ('module_list.3.BatchN...m2d.weight', tensor([1.99707, 2.0...='cuda:0')), ...])`

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolor/blob/paper/models/yolo.py

maybe you are using code of main branch and weights of paper branch.

**Comment by ehdrndd** [comment]
Oh, you're right. thanks.

I moved paper branch. it works!

**Comment by ShoaibSajid** [comment]
> https://github.com/WongKinYiu/yolor/blob/paper/models/yolo.py
> 
> maybe you are using code of main branch and weights of paper branch.

So we cannot use weights of paper branch in main branch and vice versa, even for our custom trained models ?

**Comment by RizwanMunawar** [comment]
> > https://github.com/WongKinYiu/yolor/blob/paper/models/yolo.py
> > maybe you are using code of main branch and weights of paper branch.
> 
> So we cannot use weights of paper branch in main branch and vice versa, even for our custom trained models ?

Thanks, it worked.
**Yolor-p6 main branch weights:** [yolor-p6.pt](https://drive.google.com/file/d/1Tdn3yqpZ79X7R1Ql0zNlNScB1Dv9Fp76/view?usp=sharing)
**Yolor-p6 paper branch weights:** [yolor_p6.pt](https://drive.google.com/file/d/1WyzcN1-I0n8BoeRhi_xVt8C5msqdx_7k/view?usp=sharing)
