### ISSUE TITLE
請問如何準備自己的資料集???

### ISSUE THREAD

**Issue by shyhyawJou** [WongKinYiu/yolor#106]
您好

我的資料集有參照coco.yaml 以及 coco的資料夾結構, 如下圖
![0](https://user-images.githubusercontent.com/84492341/135018355-1ae34311-07a7-4da1-8e39-ba6bae978bbe.PNG)
![2](https://user-images.githubusercontent.com/84492341/135018130-d6cb982d-67ef-4269-8c7a-8285dc6e79f7.PNG)

但跑出如下圖的錯誤, 我在猜是因為沒有資料集的 .cache 檔?
![3](https://user-images.githubusercontent.com/84492341/135018232-8c0a4ee5-7428-4dcc-986e-846e54fba56d.PNG)

請問要如何生成自己資料集 .cache?

**Comment by WongKinYiu** [comment]
請提供您的data.yaml

**Comment by shyhyawJou** [comment]
![4](https://user-images.githubusercontent.com/84492341/135023851-15fcec37-9b01-4eb0-9085-3557112ab765.PNG)

我放在 yolor-main/data 裡面, 與coco.yaml 同位置

**Comment by WongKinYiu** [comment]
程式應該會自動搜尋txt裡的圖檔建立cache檔, 您看看發生錯誤前的log並檢查txt裡的路徑, 估計是沒找到對應檔案.
