### ISSUE TITLE
请问您的implicit和用类似depthwise conv卷积有什么本质区别？

### ISSUE THREAD

**Issue by asdksc** [WongKinYiu/yolor#107]
感觉也还是学一组参数，或者和conv的乘的weight，或者和加的bias一样的功能，一样的去学习？

**Comment by WongKinYiu** [comment]
vanilla convolution 学一组参数，或者和conv的乘的weight，或者和加的bias一样的功能.
batch norm 学一组参数，或者和conv的乘的weight，或者和加的bias一样的功能，但考慮了batch資料的moving average.
attention 学一组参数，或者和conv的乘的weight，或者和加的bias一样的功能，但反映了不同特徵的重要性.
proposed implicit knowledge 学一组参数，或者和conv的乘的weight，或者和加的bias一样的功能，但加入了稀疏表示中的字典學習和隱變數模型與流型的概念.

很多方法的最終表達形式都是相同的, 但優化的目標與背後的物理意義都是不同的, 這也造成了截然不同的效果.

**Comment by asdksc** [comment]
嗯，多谢解答，毕竟不同的网络结构也是为了有不同的效果，不同的训练方法为了找更好的解。
