### ISSUE TITLE
Error while resuming training

### ISSUE THREAD

**Issue by mariusfm54** [WongKinYiu/yolor#116]
Hello,
I run a training and stopped it before it ends. When I try to resume the training using `python3 train.py --resume` I got the following error:
`Traceback (most recent call last):
  File "train.py", line 537, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 81, in train
    model = Darknet(opt.cfg).to(device)  # create
  File "yolor/models/models.py", line 530, in __init__
    self.module_defs = parse_model_cfg(cfg)
  File "yolor/utils/parse_config.py", line 13, in parse_model_cfg
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '.cfg'
`

I also try to run: `python3 train.py --cfg my_cfg.cfg --resume` but I got the same error.

Then I noticed that in train.py, l.502 there is the following line:
`opt.cfg, opt.weights, opt.resume = '', ckpt, True`
So the cfg filename is set to '', I tried to modify the line this way:
`opt.weights, opt.resume = ckpt, True`
but still got the same error. 

Do you have any clue?

**Comment by WongKinYiu** [comment]
`python3 train.py --cfg 'my_cfg.cfg' --weights 'runs/train/xxx/weights/last.pt'`

**Comment by santhraul** [comment]
This is creating another tensorboard instance. Is there any way we can continue the same training instance so that new tesorboard instance will not be cteated?

**Comment by Va2sili** [comment]
You have to use the exact same command line that the first one you used, simply replacing the weights by _last.pt_.

What are you calling tensorboard plot? 
Yes it creates a new folder every time you resume your training but the training will continue where you stopped it. At the end, the different plots in the _yolor/runs/train/name/_ folder represent the training over all the epochs for me, I do not see any different colors.

**Comment by mbl1234** [comment]
这几种方法都没有解决，怎么办 #160

**Comment by yydc-0** [comment]
python train.py  --batch-size 5 --img 1000 1000 --cfg 'cfg/yolor_p6_person.cfg' --data ./data/person.yaml  --resume './runs/train/yolor-p6-person/weights/last_298.pt' --device 0 --name yolor-p6-person --hyp hyp.scratch.1280.yaml --epochs 300 

and modify the line in this way:
opt.cfg, opt.weights, opt.resume = '', ckpt, True -> opt.cfg, opt.weights, opt.resume = check_file(opt.cfg), ckpt, True

**Comment by burak43** [comment]
@WongKinYiu @yydc-0 When I use python tune.py --cfg 'mycfg.cfg' --resume 'my_ckpt.pt', the code stuck in line `model = DDP(model, device_ids=[opt.local_rank], output_device=opt.local_rank)`. Any suggestions?

**Comment by qutyyds** [comment]
我想问一下，恢复训练时学习率会发生变化啊。如何保证延续之前的学习率呢？
