### ISSUE TITLE
Question - Training with Implicit  + Decouple Head + SimOTA + Free Anchor setting

### ISSUE THREAD

**Issue by DacDinh147** [WongKinYiu/yolor#125]
Hi author. Thank for your great work. I learn from you a lot. I read your log in YOLOV4 development and I would like to learn from your experiment in training with Implicit + Decouple Head + SimOTA + Free Anchor setting.

I reimplement your work in a new framework and adding Decouple Head + SimOTA + Free anchor on top of Implicit A + M

![W B Chart 10_20_2021, 2 23 34 AM](https://user-images.githubusercontent.com/51676233/137977679-de5de9b7-fa75-43f0-909e-fdfdf17817da.png)

Currently, I am training on COCO128 toy dataset from scratch, and the training is very unstable around 4k and 6k iteration, MAPs suddenly drop as show in the above figure. Did you experience this issue in your own training and would you please share some trick or insight to avoid this issue? I appreciate it a lot.

**Comment by voicccc** [comment]
@WongKinYiu @DacDinh147 Where are these improvements
