### ISSUE TITLE
Issues on the pretrained model

### ISSUE THREAD

**Issue by Yuuuuuuuuuuuuuuuuuummy** [WongKinYiu/yolor#13]
Hi,

Great work！
I use the *main* branch to train my model. I checked the pretrained *yolor_p6.pt* is okay. But could you provide more well-trained model for fine-tune? such as yolor_w6.pt, yolor_e6.pt....

I noticed in your *paper* branch, you provide these model, yolor-w6.pt, yolor-e6.pt....But it may not be compatible with the *main* branch code with the following error:

>ModuleNotFoundError: No module named 'models.yolo'

Hope to get your advice!

**Comment by WongKinYiu** [comment]
update yolor_w6.pt in [get_pretrain.sh](https://github.com/WongKinYiu/yolor/blob/main/scripts/get_pretrain.sh).

**Comment by Yuuuuuuuuuuuuuuuuuummy** [comment]
Thanks！
And do you have any plan for providing *yolor_e6.pt* or *yolor_d6.pt* ？

**Comment by WongKinYiu** [comment]
currently i have no enough gpus for running extra experiments.
