### ISSUE TITLE
Paper branch or main branch?

### ISSUE THREAD

**Issue by DP1701** [WongKinYiu/yolor#143]
Hello all,

I have a few questions because I am a little confused. I have a costum dataset (3 classes, 2800 images) which I would like to use for training.

Should I clone the main branch or the paper branch? In the paper branch, for example, there is the file yolor-p6.yaml in the model/ folder, while in the main branch there is the file yolov4_p6.cfg in the cfg/ folder. Which one should I use?

In the data/ folder I also find the two files hyp.finetune.1280.yaml and hyp.scratch.1280.yaml. Which one do you recommend to take if I take the weights from the file yolor_p6.pt? Or should I rather train from scratch?

Another question: What makes tune.py?

Sorry for all the questions, but I would like to understand this.

**Comment by Deadpool5549** [comment]
Hi, I have used both branches for training (main branch for training p6, paper branch for d6) ,I don't think there will be any difference, but make sure you use the same weights for respective branch.
Use finetuning(hyp.finetune (it further augments your images)) after completing few hundred epochs, Training from scratch takes time, so use pretrained weight.
From what I know tune.py uses different mosaics ,with images scaled differently
for your reference, this is a mosaic(batch size=16) for train.py
![image](https://user-images.githubusercontent.com/67370921/145071698-9382d922-1421-4ee8-8eae-9b50c685cce9.png)

**Comment by DP1701** [comment]
Thank you for the explanation!
