### ISSUE TITLE
How to predict all the objects in an image that contains handreds of objects?

### ISSUE THREAD

**Issue by hughwyc** [WongKinYiu/yolor#150]
I use the YOLOR P6 to predict an image like this:

![003](https://user-images.githubusercontent.com/61838645/145145061-b40bcf74-52bc-4445-b343-0171f423597b.jpg)

The command that I run is as follows:
`python detect.py --source inference/images/003.jpg --cfg cfg/yolor_p6.cfg --weights yolor_p6.pt --conf 0.25 --img-size 1280 --device 0`

But only few of objets in the image was detected ( 23 persons, 5 handbags ) , the input image size is 1920x1280. Does anyone konws how to get an ideal result by changing some parameters in the code?

**Comment by kadmor** [comment]
You can try to reduce --conf

**Comment by hughwyc** [comment]
thanks, it works.

> You can try to reduce --conf
