### ISSUE TITLE
New Updates to Inference Speed and mAP

### ISSUE THREAD

**Issue by rahul-kota** [WongKinYiu/yolor#154]
Greetings, I was wondering if you could please share some of the details of your improvements to the YOLOR models since adapting to the new 300 epoch training schedule. Even just a quick summary would be greatly appreciated.

**Comment by WongKinYiu** [comment]
for 300 epoch training schedule:
https://github.com/WongKinYiu/yolor/issues/82#issuecomment-905195926

for inference speed:
our data are stored in network file system, so when doing inference, the program load images via network.
we found that the network file system is the bottleneck of inference speed, and then create temp file system to store data to solve the problem.

**Comment by rahul-kota** [comment]
Thanks for the help! For reference, it appears the mAP boost I was wondering about was from this method: https://openaccess.thecvf.com/content/ICCV2021W/LPCV/papers/Wang_Exploring_the_Power_of_Lightweight_YOLOv4_ICCVW_2021_paper.pdf .
