### ISSUE TITLE
W&B log look weird

### ISSUE THREAD

**Issue by 1chimaruGin** [WongKinYiu/yolor#166]
W&B validation loss start from 0.

![W B Chart 1_3_2022, 8_55_32 PM](https://user-images.githubusercontent.com/35499653/147943827-49a53702-fb61-4b86-ae7a-7af4fa8238d2.png)

How can I fix this?

**Comment by LoveDH** [comment]
I think because the model doesn't validate about 3 epochs at first.

**Comment by 1chimaruGin** [comment]
Thank you. I have solved the problem.
