### ISSUE TITLE
minimum GPU VRAM to use YOLOR

### ISSUE THREAD

**Issue by rodthebuilder1** [WongKinYiu/yolor#177]
Hi,

I am limited to a rtx 2070 super with 8GB of VRAM, all on windows 10

I was wondering if it would be possible to run YOLOR on it ? OR would I need more Vram? Is it possible to use cpu RAM to complement VRAM ?

Thanks

**Comment by susanin1970** [comment]
I tested the YOLOR-CSP-X inference on a single frame on a GTX 1080 Ti with 11Gb of VRAM
Inferaece was successful

**Comment by atamazian** [comment]
Your question is quite vague. First of all, do you want to train models, or you just want to do inference? Inference requires less GPU VRAM.
