### ISSUE TITLE
The function of the tune.py file?

### ISSUE THREAD

**Issue by ilem777** [WongKinYiu/yolor#2]
May I ask what is the function of the [tune.py](https://github.com/WongKinYiu/yolor/blob/0cdcea3fbfc7cc7cee39d5bd9a87b3441e4e416d/tune.py) file?
What is the difference between [tune.py](https://github.com/WongKinYiu/yolor/blob/0cdcea3fbfc7cc7cee39d5bd9a87b3441e4e416d/tune.py) and [train.py](https://github.com/WongKinYiu/yolor/blob/0cdcea3fbfc7cc7cee39d5bd9a87b3441e4e416d/train.py)?

**Comment by WongKinYiu** [comment]
The only difference is that [train.py](https://github.com/WongKinYiu/yolor/blob/0cdcea3fbfc7cc7cee39d5bd9a87b3441e4e416d/train.py) use mosaic4 while [tune.py](https://github.com/WongKinYiu/yolor/blob/0cdcea3fbfc7cc7cee39d5bd9a87b3441e4e416d/tune.py) usw mosaic9.

![schedule](https://raw.githubusercontent.com/WongKinYiu/yolor/main/figure/schedule.png)

**Comment by ilem777** [comment]
Understood, thank you.
