### ISSUE TITLE
how to reproduce yolor-d6-paper-573.pt?

### ISSUE THREAD

**Issue by aliencaocao** [WongKinYiu/yolor#239]
I downloaded this checkpoint and ran inference using` python test.py --img 1280 --batch 16 --conf 0.001 --iou 0.65 --device 0 --data data/coco.yaml --weights yolor-d6-paper-573.pt --name yolor_d6_val --verbose` but can only get 55.8 mAP on coco2017 val. How to reproduce 57.3?

```
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95: 100%|█| 313/313 [03:44<00
                 all       5e+03    3.63e+04       0.488       0.812       0.743       0.558
```

**Comment by Splendon** [comment]
Map 57.3 is running on test-dev2017, not coco2017 val.
