### ISSUE TITLE
About num of filters in .cfg file

### ISSUE THREAD

**Issue by e4exp** [WongKinYiu/yolor#25]
Hello, I'm trying to train YOLOR on my custom data.

In previous versions of YOLO, we set `(classes + 5) * 3` filters in `[convolution]` layers before `[yolo]` layers.
I think we should do the same thing to 4 `[implicit_mul]` layers in `yolor_p6.cfg` in your work.
Is this collect?

Thank you.

**Comment by WongKinYiu** [comment]
yes, you are correct.

**Comment by e4exp** [comment]
Thank you for your quick response, I understood.

**Comment by qutyyds** [comment]
YOLORp6.yaml 中怎么修改呢？
