### ISSUE TITLE
SyntaxError while testing on jetson xavier nx

### ISSUE THREAD

**Issue by cnr0724** [WongKinYiu/yolor#28]
```
  File "test.py", line 155
    for *xyxy, conf, cls in x:
        ^
SyntaxError: invalid syntax
```

I know that the code is great(syntax error didn't happen when ran on the server), but I get syntaxerror when running test.py on jetson xavier nx. What should I do?

**Comment by cnr0724** [comment]
I think it's related to the package issue, but I'm not sure...

**Comment by WongKinYiu** [comment]
i guess it due to python version too new.

**Comment by cnr0724** [comment]
You were right. I was running the code on python2. Thanks for helping me!T.T
