### ISSUE TITLE
How to change cfg for custom dataset with different number of classes?

### ISSUE THREAD

**Issue by TheConstant3** [WongKinYiu/yolor#34]
[Darknet repo](https://github.com/AlexeyAB/darknet) has guide "How to train (to detect your custom objects)", where described how change count filters and other parameters for custom dataset. If i change in yolor_p6.cfg number of classes to 2, i get error 
```
  File "/workspace/yolor/models/models.py", line 400, in forward
    p = p.view(bs, self.na, self.no, self.ny, self.nx).permute(0, 1, 3, 4, 2).contiguous()  # prediction
RuntimeError: shape '[4, 3, 7, 80, 80]' is invalid for input of size 6528000
```

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolor/issues/16

https://github.com/WongKinYiu/yolor/issues/25

**Comment by TheConstant3** [comment]
Sorry, couldn't find it

Thank you so much!
