### ISSUE TITLE
torchtext 0.10.0 is incompatible. 

### ISSUE THREAD

**Issue by totoadel** [WongKinYiu/yolor#38]
ERROR: torchtext 0.10.0 has requirement torch==1.9.0, but you'll have torch 1.7.0 which is incompatible.

**Comment by WongKinYiu** [comment]
pytorch 1.9 is not yet supported. currently supported version are 1.7 and 1.8.

**Comment by totoadel** [comment]
You means, this is not error
The code can work even though.

**Comment by akashAD98** [comment]
cuda 11.4 is supported for yolor?

**Comment by WongKinYiu** [comment]
yes, in my experiment pytorch 1.10.0a0+3fd9dcf with cuda 11.4.1 is ok.

and in actually pytorch 1.9.0a0+df837d0 with cuda 11.2.1 is ok, but pytorch 1.9.0a0+c3d40fd with 11.3.1 has problem.

**Comment by akashAD98** [comment]
@WongKinYiu thanks for your kind info.
