### ISSUE TITLE
Error in Export onnx

### ISSUE THREAD

**Issue by totoadel** [WongKinYiu/yolor#39]
`!python models/export.py --weights yolor_p6.pt --img-size 512 --cfg cfg/yolor_p6.cfg`

i got this error

Traceback (most recent call last):
  File "models/export.py", line 5, in <module>
    from utils.google_utils import attempt_download
ModuleNotFoundError: No module named 'utils'

**Comment by totoadel** [comment]
Thank you for your not replying

**Comment by WongKinYiu** [comment]
there are some solutions to export onnx in other issues, just search 'onnx' and you could find solution.
