### ISSUE TITLE
How to use yolor in mmdetection?

### ISSUE THREAD

**Issue by likyoo** [WongKinYiu/yolor#40]
Thanks for your great work! 
I noticed the "mmdet" branch, could you describe how to use yolor in mmdet?

**Comment by WongKinYiu** [comment]
Hello, the code of mmdet implementation is not yet released.

**Comment by likyoo** [comment]
Looking forward to it!

**Comment by Tim-Hung** [comment]
Hi, thanks for the great work first!
Are there any updates when you plan to release the mmdet implementation?
