### ISSUE TITLE
Training on custom dataset and labels

### ISSUE THREAD

**Issue by devloper13** [WongKinYiu/yolor#45]
I have a dataset of my own which has 8 labels, completely different from the coco labels. I changed the data/coco.names and data/coco.yaml accordingly. But I get an index error:
```
Traceback (most recent call last):
  File "train.py", line 537, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 344, in train
    log_imgs=opt.log_imgs if wandb else 0)
  File "/home/ubuntu/yolor/test.py", line 226, in test
    plot_images(img, output_to_target(output, width, height), paths, f, names)  # predictions
  File "/home/ubuntu/yolor/utils/plots.py", line 164, in plot_images
    cls = names[cls] if names else cls
IndexError: list index out of range
```

I tried printing the detection classes and its in the range 0-79 i.e coco labels. But why is this happening when I completely changed the labels?

Training command:
`python train.py --batch-size 1 --img 1280 1280 --data coco.yaml --cfg cfg/yolor_p6.cfg --weights yolor_p6.pt --device 0 --name yolor_p6_digit --hyp hyp.scratch.1280.yaml --epochs 5`

**Comment by LaoGanGit** [comment]
你好，我也遇到这个问题，请问您找到解决方法了吗

**Comment by neel04** [comment]
Hey, how did you solve this?

**Comment by dripdropdr** [comment]
How did you solve this? I have the same problem, too.

**Comment by LoveDH** [comment]
In coco.names, there is an empty line at last line.
![Screenshot from 2022-03-17 10-31-42](https://user-images.githubusercontent.com/44254662/158718710-8cfb85db-ec50-408e-99c4-5683fff7e5af.png)
maybe you didn't create the last empty line. It worked for me
