### ISSUE TITLE
How and why to use mish-cuda and pytorch-wavelets

### ISSUE THREAD

**Issue by JayantGoel001** [WongKinYiu/yolor#59]
Hello
I saw in yolor it was given we can use mish-cuda and pytorch-wavelet how we can install and build it.
So Do we require to do anything other than that or That's it?

And What is the use of These two with yolor?

**Comment by WongKinYiu** [comment]
```
# install mish-cuda if you want to use mish activation
# https://github.com/thomasbrandon/mish-cuda
# https://github.com/JunnYu/mish-cuda
cd /
git clone https://github.com/JunnYu/mish-cuda
cd mish-cuda
python setup.py build install

# install pytorch_wavelets if you want to use dwt down-sampling module
# https://github.com/fbcotter/pytorch_wavelets
cd /
git clone https://github.com/fbcotter/pytorch_wavelets
cd pytorch_wavelets
pip install .
```

to use mish
```
[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=mish
```

to use dwt
```
[dwt]
```

**Comment by Mut1nyJD** [comment]
Seen any benefit in using Mish instead of Silu? So my guess is that there wasn't any otherwise it would be in the default config?

**Comment by JayantGoel001** [comment]
> Seen any benefit in using Mish instead of Silu? So my guess is that there wasn't any otherwise it would be in the default config?

Ya there was no use of it it even decreased our confidence level and started giving the wrong result
