### ISSUE TITLE
Precision, Recall and mAP seems incoherent

### ISSUE THREAD

**Issue by yusiyoh** [WongKinYiu/yolor#80]
Hello, 

I am training YOLOR-D6, I obtain precision, recall and mAP results from test.py with following command using paper branch:
python3 test.py --weights ./runs/train/yolor-d6-1280size-multiGPU/weights/best.pt --img 1280 --verbose --data data/dtld_test.yaml --batch 32 --task test --conf 0.4 --iou 0.5 

Here is the result: 
![image](https://user-images.githubusercontent.com/6302128/130422296-d396cac6-ca9a-47ee-92a5-c858bbea18f6.png)
I think the mAP0.5 is very high with those recall values. Is there a mistake in metrics.py? Or do I have to run test.py with different options?
Thank you.

**Comment by yusiyoh** [comment]
Another point is that when I change the confidence threshold, mAP also changes significantly. Should not it be the same for different conf-thres values? Otherwise, one model can have better mAP with one confidence threshold, another one would have better mAP with another confidence level, which is strange.

**Comment by yusiyoh** [comment]
Yet another strange thing is that when I reduce conf-thres the mAP decreases significantly instead of increasing ( It is expected to increase with reducing conf-thres).
The first one is with default conf-thres (0.001):
![image](https://user-images.githubusercontent.com/6302128/130646320-3ddff0f1-d66c-4668-a238-706c1253b992.png)
Second one is with 0.4 conf-thres:
![image](https://user-images.githubusercontent.com/6302128/130646473-6a32cfba-17c7-4790-88d2-c179261d86fe.png)

**Comment by yusiyoh** [comment]
I have changed the metrics.py according to https://github.com/ultralytics/yolov5/blob/master/utils/metrics.py and the mAP are very different.
Default YOLOR:
![image](https://user-images.githubusercontent.com/6302128/130667913-43f7c4b1-38fa-4335-bfcb-9d6b14168802.png)
YOLOV5 metrics:
![image](https://user-images.githubusercontent.com/6302128/130667989-4035d37f-9da3-4c5b-8322-729c2d02a4ae.png)

Which one is wrong and why?

**Comment by WongKinYiu** [comment]
thanks, i change these two lines with your suggestion, but i think two metrics.py will still output different results.
