### ISSUE TITLE
New training schedule

### ISSUE THREAD

**Issue by rahul-kota** [WongKinYiu/yolor#82]
On the 'paper' branch, you share new results with a new 300 epoch training schedule. Could you please share the details of the new schedule such as hyperparameters and other techniques employed?

**Comment by WongKinYiu** [comment]
This is new training schedule, some codes need to be modified and currently I have no enough time to do that.
If you want to use it, I think you can finish 95% of them by combining existing code.
Or I think I will have time to integrate the code after October.
![image](https://user-images.githubusercontent.com/12152972/130731329-f885846c-e3a7-4ea2-88f2-7999a7b3b2cb.png)

**Comment by rahul-kota** [comment]
Thank you very much, this is exactly what I was looking for.
