### ISSUE TITLE
Detection differences between YOLO PyTorch frameworks?

### ISSUE THREAD

**Issue by Va2sili** [WongKinYiu/yolor#83]
I recently used ultralytics YOLOv3 archived repository to convert darknet weights to pytorch weights. I then ran inference on a set of images.
Then, I used this yolor repository with the converted YOLOv3 Pytorch weights (and cfg file) to run inference on the same dataset: it appears results are way better, detection is more accurate. 
I am wondering why results are better with this repository: what's the difference between these two detectors? How comes that I can run inference using YOLOv3 weights with a YOLOR repository? I assume YOLOR reads my cfg file and detect these are YOLOv3 weights and then run YOLOv3 inference on my images but why are the results better than with the YOLOv3 repo then?

**Comment by WongKinYiu** [comment]
could you show example output of two repository?

**Comment by Va2sili** [comment]
Sure. This is what I get with YOLOR (accurately):
image 593/1599 ../python_scripts/image/3655.jpg: 768x1280 Done. (0.022s)
image 594/1599 ../python_scripts/image/3660.jpg: 768x1280 Done. (0.022s)
image 595/1599 ../python_scripts/image/3665.jpg: 768x1280 Done. (0.022s)
image 596/1599 ../python_scripts/image/3670.jpg: 768x1280 Done. (0.022s)
image 597/1599 ../python_scripts/image/3675.jpg: 768x1280 Done. (0.022s)
image 598/1599 ../python_scripts/image/3680.jpg: 768x1280 Done. (0.022s)
image 599/1599 ../python_scripts/image/3685.jpg: 768x1280 Done. (0.022s)
image 600/1599 ../python_scripts/image/3690.jpg: 768x1280 Done. (0.022s)
image 601/1599 ../python_scripts/image/3695.jpg: 768x1280 1 Diamonds, Done. (0.022s)
image 602/1599 ../python_scripts/image/370.jpg: 768x1280 Done. (0.022s)
image 603/1599 ../python_scripts/image/3700.jpg: 768x1280 1 Diamonds, Done. (0.022s)
image 604/1599 ../python_scripts/image/3705.jpg: 768x1280 1 Diamonds, 1 Rectangulars, 1 WarningSpeedLimits, Done. (0.022s)
image 605/1599 ../python_scripts/image/3710.jpg: 768x1280 2 Diamonds, 1 Rectangulars, 1 WarningSpeedLimits, Done. (0.022s)
image 606/1599 ../python_scripts/image/3715.jpg: 768x1280 1 Diamonds, 1 Rectangulars, 1 WarningSpeedLimits, Done. (0.022s)
image 607/1599 ../python_scripts/image/3720.jpg: 768x1280 1 Diamonds, 1 Rectangulars, 1 WarningSpeedLimits, Done. (0.022s)
image 608/1599 ../python_scripts/image/3725.jpg: 768x1280 Done. (0.022s)
image 609/1599 ../python_scripts/image/3730.jpg: 768x1280 Done. (0.022s)
image 610/1599 ../python_scripts/image/3735.jpg: 768x1280 Done. (0.022s)
image 611/1599 ../python_scripts/image/3740.jpg: 768x1280 1 Rectangulars, Done. (0.022s)
image 612/1599 ../python_scripts/image/3745.jpg: 768x1280 1 Rectangulars, Done. (0.022s)
image 613/1599 ../python_scripts/image/375.jpg: 768x1280 Done. (0.022s)
image 614/1599 ../python_scripts/image/3750.jpg: 768x1280 Done. (0.022s)
image 615/1599 ../python_scripts/image/3755.jpg: 768x1280 1 Rectangulars, Done. (0.023s)
image 616/1599 ../python_scripts/image/3760.jpg: 768x1280 2 Rectangulars, Done. (0.023s)
image 617/1599 ../python_scripts/image/3765.jpg: 768x1280 Done. (0.022s)

This is what I get with the YOLOv3 repo:
image 593/1599 ../../python_scripts/image/3655.jpg: 288x512 Done. (0.011s)
image 594/1599 ../../python_scripts/image/3660.jpg: 288x512 Done. (0.011s)
image 595/1599 ../../python_scripts/image/3665.jpg: 288x512 Done. (0.011s)
image 596/1599 ../../python_scripts/image/3670.jpg: 288x512 Done. (0.011s)
image 597/1599 ../../python_scripts/image/3675.jpg: 288x512 Done. (0.011s)
image 598/1599 ../../python_scripts/image/3680.jpg: 288x512 Done. (0.011s)
image 599/1599 ../../python_scripts/image/3685.jpg: 288x512 Done. (0.011s)
image 600/1599 ../../python_scripts/image/3690.jpg: 288x512 Done. (0.011s)
image 601/1599 ../../python_scripts/image/3695.jpg: 288x512 Done. (0.011s)
image 602/1599 ../../python_scripts/image/370.jpg: 288x512 Done. (0.011s)
image 603/1599 ../../python_scripts/image/3700.jpg: 288x512 Done. (0.011s)
image 604/1599 ../../python_scripts/image/3705.jpg: 288x512 Done. (0.011s)
image 605/1599 ../../python_scripts/image/3710.jpg: 288x512 1 Diamonds, Done. (0.011s)
image 606/1599 ../../python_scripts/image/3715.jpg: 288x512 1 Diamonds, 1 Rectangulars, Done. (0.011s)
image 607/1599 ../../python_scripts/image/3720.jpg: 288x512 1 Diamonds, Done. (0.011s)
image 608/1599 ../../python_scripts/image/3725.jpg: 288x512 Done. (0.011s)
image 609/1599 ../../python_scripts/image/3730.jpg: 288x512 Done. (0.011s)
image 610/1599 ../../python_scripts/image/3735.jpg: 288x512 Done. (0.011s)
image 611/1599 ../../python_scripts/image/3740.jpg: 288x512 Done. (0.011s)
image 612/1599 ../../python_scripts/image/3745.jpg: 288x512 1 Rectangulars, Done. (0.011s)
image 613/1599 ../../python_scripts/image/375.jpg: 288x512 Done. (0.011s)
image 614/1599 ../../python_scripts/image/3750.jpg: 288x512 Done. (0.011s)
image 615/1599 ../../python_scripts/image/3755.jpg: 288x512 Done. (0.011s)
image 616/1599 ../../python_scripts/image/3760.jpg: 288x512 Done. (0.011s)
image 617/1599 ../../python_scripts/image/3765.jpg: 288x512 Done. (0.011s)

**Comment by WongKinYiu** [comment]
oh, i mean output image with prediction.

**Comment by WongKinYiu** [comment]
by the way, the main reason i think it is due to inference size.
in yolor, u use 768x1280, and in yolov3, u use 288x512.

**Comment by Va2sili** [comment]
Oh I see. But this size was not given by me, the repo computed it themselves. This raises several questions for me:

- If these sizes were the same, I would get similar inference results? 

- I see that your YOLOv4 Pytorch repo is also compatible with darknet cfg file. Can I use then either yolor or yolov4 repo to run inference on YOLOv3  darknet weights? The YOLO version differences is not a problem? The results should be similar?

- Is that correct that the difference between these different YOLO PyTorch repo is mainly about the training: YOLOR generates YOLOR weights, YOLOv4 generates YOLOv4 weights, YOLOv5 generates YOLOv5 weights... ?

Sorry, here are the samples:
YOLOR:
![115](https://user-images.githubusercontent.com/30473152/130771874-da57a384-3e2c-414c-b764-09eface58fa5.jpg)
![120](https://user-images.githubusercontent.com/30473152/130771876-f2397950-6ebc-4807-b84a-c847bc7b4825.jpg)
![125](https://user-images.githubusercontent.com/30473152/130771878-d5286ce9-88ae-403c-9764-e84eb0daaa70.jpg)
![130](https://user-images.githubusercontent.com/30473152/130771879-21192ea4-eb21-4940-a666-4ce794905d5e.jpg)
![135](https://user-images.githubusercontent.com/30473152/130771880-534a19b3-0125-4ad5-b56d-a7abadcb7b7d.jpg)
![140](https://user-images.githubusercontent.com/30473152/130771881-38ee6f51-8700-4467-915c-912a75f17d6d.jpg)
![145](https://user-images.githubusercontent.com/30473152/130771882-2ce16596-218b-4679-b012-3f656e6ec9ad.jpg)
![150](https://user-images.githubusercontent.com/30473152/130771883-dbf419f3-8671-46a8-98cb-ae3983023b2a.jpg)
![155](https://user-images.githubusercontent.com/30473152/130771885-f560a68a-4371-4dfc-a912-ac8f9ff8ec7a.jpg)
![160](https://user-images.githubusercontent.com/30473152/130771886-287d00aa-e26c-49a4-887c-1fd0698e7fe4.jpg)
![110](https://user-images.githubusercontent.com/30473152/130771887-092ad87b-1f0c-4318-998a-37b6aa6f37a7.jpg)

YOLOv3:
![120](https://user-images.githubusercontent.com/30473152/130772077-ee12c2b7-6bd3-435a-9421-70dea8d2c259.jpg)
![125](https://user-images.githubusercontent.com/30473152/130772079-014aba59-2393-4106-b6e2-73ca182b9462.jpg)
![130](https://user-images.githubusercontent.com/30473152/130772081-d8926f08-26fe-45eb-bc4a-1704aeff0606.jpg)
![135](https://user-images.githubusercontent.com/30473152/130772082-4e60882a-7da9-46c0-9857-f654ec4994d5.jpg)
![140](https://user-images.githubusercontent.com/30473152/130772084-c3eb035e-b944-4de5-af8c-f265a2a3bcab.jpg)
![145](https://user-images.githubusercontent.com/30473152/130772086-e16975db-6db0-4b21-b187-42ff38444834.jpg)
![150](https://user-images.githubusercontent.com/30473152/130772089-594ddf95-e75b-402b-950a-5da4dc756395.jpg)
![155](https://user-images.githubusercontent.com/30473152/130772091-2e858755-646e-4250-abb9-fcf7b018fc7b.jpg)
![160](https://user-images.githubusercontent.com/30473152/130772092-013a68ac-ca89-481d-9e5b-48ff5f522db8.jpg)
![110](https://user-images.githubusercontent.com/30473152/130772093-a2c9cd30-4921-41fb-9193-1996f7ea31c8.jpg)
![115](https://user-images.githubusercontent.com/30473152/130772095-55d03f6c-d3f7-4386-88f3-8244fbe9c957.jpg)

**Comment by Va2sili** [comment]
So you were right, the inference sizes I used were the default ones, that's why they were different. This link was useful to understand inference size: https://github.com/ultralytics/yolov3/issues/232
It seems that the --img-size that should be chosen is the biggest dimension of the image I want to use.

With identical inference sizes I get similar result even though one class is never detected using YOLOv3 repo while it is detected using YOLOR... This is probably a bug in YOLOv3 repo as I think I should be able to use any Pytorch repo for inference and still get the same results (YOLOv3 or YOLOv4 or YOLOR).
