### ISSUE TITLE
大佬，bacth_size=1,Out of memory?

### ISSUE THREAD

**Issue by crazybill-first** [WongKinYiu/yolor#88]
大佬，您好，我在使用自定义数据集训练yolor_p6时出现 cuda out of memory,我把batch_size=1依然会出现。我很奇怪。
train command:
`python train.py --batch-size 1 --img 416 416 --data person.yaml --cfg cfg/yolor_p6.cfg --weights '' --device 2 --name yolor_p6 --hyp hyp.scratch.416.yaml --epochs 300`
log
![image](https://user-images.githubusercontent.com/57820960/131679573-f796dadc-f2b0-49a2-9380-06839f4e152a.png)
result
![image](https://user-images.githubusercontent.com/57820960/131678887-8be231e6-c04a-4de9-8592-8aea72f79868.png)
是我哪步出错了吗？

**Comment by crazybill-first** [comment]
额。。。。
并没有找到相关的进程，我重启机器后就可以训练了 -_- !!!。
另外
README中 Multiple GPU training command适用windows吗？

**Comment by crazybill-first** [comment]
因为我试了一下多GPU训练，由于NCCL的原因出错。这个问题只会出现在windows上吗？

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/yolor/blob/main/train.py#L518

可以試試看把 nccl 改成 gloo.

**Comment by crazybill-first** [comment]
不好意思，忘记回复您了。谢谢您的建议，使用gloo后已经可以多卡训练了。不过又出现了一个问题，我用了4张卡，结果打开GPU信息，发现只用了两个，我正在看代码找原因。
我已经开始训练行人检测的模型，训练完成后 我会把结果展示出来

**Comment by crazybill-first** [comment]
不好意思，由于某些原因我的结果不能展示出来，我会关闭这个问题
